[package]
name = "pbfextractor"
version = "0.1.0"
authors = ["Florian Barth <florianbarth@gmx.de>"]
edition = "2018"

[dependencies]
byteorder = "1"
clap = "4"
flate2 = "1"
osmpbfreader = "0.16"
rand = "0.8"
smartstring = { version = "1.0.1", features = ["serde", "arbitrary"] }
